title: Effry Muhammad # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data and Machine Learning
  <br>
  Research:
  - Computer Vision
  - Financial Market
  - Predictive Analytics
  - Time-series Deep Learning
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
